language: node_js

node_js:
  - "lts/*"
  - "stable"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install imagemagick ghostscript poppler-utils graphicsmagick

before_script:
  - npm link

deploy:
  skip_cleanup: true
  provider: npm
  email: reschan12345+npm@gmail.com
  api_key: $NPM_API_KEY
  on:
    repo: ReschAndr/html-to-pdf
